---
- name: Ensuring AppArmor is disabled (Ubuntu 14+)
  shell: "service apparmor stop && update-rc.d -f apparmor remove"

- name: Bootstraping Download Directory for RADIUSDesk Sources (Ubuntu 14+)
  file:
    path={{ temp_src_dir }}
    state=directory
    mode=0777
  
- name: Ensuring Apache is not installed (Ubuntu 14+)
  apt:
    name={{ apache_pkg_name }}
    state=absent

- name: Installing Nginx (Ubuntu 14+)
  apt:
    name={{ nginx_pkg_name }}
    state=installed
    update_cache=yes

- name: Installing PHP5 packages (Ubuntu 14+)
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: "{{ rd_php5_pkgs }}"
  when: "ansible_distribution_major_version < '13'"

- name: Adding Adre PHP7 PPA (Ubuntu 14+)
  apt_repository:
    repo="{{ php7_apt_ppa_repo }}"
    state=present
  when: "ansible_distribution_release == 'trusty'"

- name: Installing PHP7 packages (Ubuntu 14)
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: "{{ rd_php7_trusty_pkgs }}"
  when: "ansible_distribution_release == 'trusty'"

- name: Installing PHP7 packages (Ubuntu 16+)
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: "{{ rd_php7_pkgs }}"
  when: ansible_distribution_major_version >= "16" and ansible_distribution_major_version < "17"

- name: Installing PHP7.2 packages (Ubuntu 14+)
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: "{{ rd_php72_pkgs }}"
  when: "ansible_distribution_major_version >= '17'"

- name: Installing RadiusDesk packages (Ubuntu 14+)
  apt:
    name={{ item }}
    state=installed
    force=yes
    update_cache=yes
  with_items: "{{ rd_pkgs }}"
  notify:
    - Start Nginx
    - Start PHP-FPM
  when: "ansible_distribution_major_version < '13'"

- name: Installing RadiusDesk packages (Ubuntu 16)
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: "{{ rd_pkgs }}"
  notify:
    - Start Nginx
    - Start PHP7-FPM
  when: "ansible_distribution_major_version <= '16'"

- name: Installing RadiusDesk packages (Ubuntu 17+)
  apt:
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: "{{ rd_pkgs }}"
  notify:
    - Start Nginx
    - Start PHP72-FPM
  when: "ansible_distribution_major_version >= '17'"

- name: Configuring PHP5-FPM to use UNIX sockets (Ubuntu 14+)
  template:
    src="nginx/php_fpm.www.conf.j2"
    dest={{ php_fpm_config }}
  when: "ansible_distribution_major_version < '13'"

- name: Configuring PHP7-FPM to use UNIX sockets (Ubuntu 14+)
  template:
    src="nginx/php_fpm.www.conf.j2"
    dest={{ php7_fpm_config }}
  when: "ansible_distribution_major_version <= '16'"

- name: Configuring PHP7.2-FPM to use UNIX sockets (Ubuntu 14+)
  template:
    src="nginx/php_fpm.www.conf.j2"
    dest={{ php72_fpm_config }}
  when: "ansible_distribution_major_version >= '17'"

- name: Configuring Nginx to use UNIX sockets (Ubuntu 14+)
  template:
    src="nginx/nginx.default.conf.j2"
    dest={{ nginx_default_config }}

- name: Configuring Nginx for RadiusDesk Web Compression (Ubuntu 14+)
  template:
    src="nginx/nginx.conf.j2"
    dest={{ nginx_config }}

- name: Restarting RadiusDesk services for PHP5 (Ubuntu 14+)
  service:
    name={{ item }}
    state=restarted
  with_items:
    - "{{ nginx_pkg_name }}"
    - "{{ php_fpm_service_name }}"
  when: "ansible_distribution_major_version < '13'"

- name: Restarting RadiusDesk services for PHP7 (Ubuntu 14+)
  service:
    name={{ item }}
    state=restarted
  with_items:
    - "{{ nginx_pkg_name }}"
    - "{{ php7_fpm_service_name }}"
  when: "ansible_distribution_major_version <= '16'"

- name: Restarting RadiusDesk services for PHP7.2 (Ubuntu 14+)
  service:
    name={{ item }}
    state=restarted
  with_items:
    - "{{ nginx_pkg_name }}"
    - "{{ php72_fpm_service_name }}"
  when: "ansible_distribution_major_version >= '17'"

- name: Downloading CakePHP Source from Github (Ubuntu 14+)
  git: 
    dest={{ temp_src_dir }}/cake2
    repo={{ cakephp_git_repo }}
    update=no
    version=2.7.9

- name: Copying CakePHP Source to Webroot (Ubuntu 14+)
  shell: cp -a {{ temp_src_dir | quote }}/cake2 {{ nginx_webroot | quote }}/cake2

- name: Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu 14+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_cake_svn_repo }} {{ temp_src_dir }}/rd_cake

- name: Copying RadiusDesk CakePHP App Source to Webroot (Ubuntu 14+)
  shell: cp -a {{ temp_src_dir | quote }}/rd_cake {{ nginx_webroot | quote }}/cake2/

- name: Downloading RadiusDesk CakePHP 3 Source from Subversion (Ubuntu 14+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_cake3_svn_repo }} {{ temp_src_dir }}/cake3

- name: Copying RadiusDesk CakePHP 3 Source to Webroot (Ubuntu 14+)
  shell: cp -a {{ temp_src_dir | quote }}/cake3 {{ nginx_webroot | quote }}/cake3

- name: Downloading RadiusDesk Viewer Source from Subversion (Ubuntu 14+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_svn_repo }} {{ temp_src_dir }}/rd

- name: Copying RadiusDesk Viewer Source to Webroot (Ubuntu 14+)
  shell: cp -a {{ temp_src_dir | quote }}/rd {{ nginx_webroot | quote }}/

- name: Downloading RadiusDesk Login Source from Subversion (Ubuntu 14+)
  shell: svn checkout -r {{ rd_svn_revision }} {{ rd_login_svn_repo }} {{ temp_src_dir }}/login

- name: Copying RadiusDesk Login Source webroot (Ubuntu 14+)
  shell: cp -a {{ temp_src_dir | quote }}/login {{ nginx_webroot | quote }}/

- name: Configuring UAM Service for RadiusDesk Login (Ubuntu 14+)
  template:
    dest="{{ nginx_webroot }}/login/services/uam.php"
    src="rd/uam.php.j2"

- name: Checking if we already downloaded ExtJS 6.2 sources (Ubuntu 14+)
  stat:
    path="{{ temp_src_dir }}/ext-6-2-sencha_cmd.tar.gz"
  register: extjs_src

- name: Downloading ExtJS 6.2 sources from Subversion (Ubuntu 14+)
  get_url:
    url={{ extjs_62_src_url }}
    dest="{{ temp_src_dir }}/ext-6-2-sencha_cmd.tar.gz"
    validate_certs=no
  when: "extjs_src.stat.exists == False or extjs_src.stat.md5 != '{{ extjs_62_src_md5_sum }}'"

- name: Extracting ExtJS 6.2 archive for RadiusDesk Viewer (Ubuntu 14+)
  unarchive:
    src="{{ temp_src_dir }}/ext-6-2-sencha_cmd.tar.gz"
    dest={{ nginx_webroot }}/rd/
    owner={{ web_user }}
    group={{ web_group }}
    mode=0664
    copy=no

- name: Updating Webroot ownership and permissions (Ubuntu 14+)
  file:
    path={{ nginx_webroot }}
    owner={{ web_user }}
    group={{ web_group }}
    mode=0775
    state=directory
    recurse=yes

- name: Fix PHP5 Default Timezone
  lineinfile: 
    dest="{{ php_config_file }}"
    line='date.timezone = {{ php_timezone }}'
    regexp='^;date.timezone'
  when: "ansible_distribution_major_version < '13'"

- name: Fix PHP7 Default Timezone
  lineinfile: 
    dest="{{ php7_config_file }}"
    line='date.timezone = {{ php_timezone }}'
    regexp='^;date.timezone'
  when: "ansible_distribution_major_version <= '16'"

- name: Fix PHP7.2 Default Timezone
  lineinfile: 
    dest="{{ php72_config_file }}"
    line='date.timezone = {{ php_timezone }}'
    regexp='^;date.timezone'
  when: "ansible_distribution_major_version >= '17'"

- name: Ensuring Nginx is Started (Ubuntu 14+)
  service:
    name={{ nginx_service_name }}
    state=started

- name: Ensuring PHP5-FPM is Started (Ubuntu 14+)
  service:
    name={{ php_fpm_service_name }}
    state=started
  when: "ansible_distribution_major_version < '13'"

- name: Ensuring PHP7-FPM is Started (Ubuntu 14+)
  service:
    name={{ php7_fpm_service_name }}
    state=started
  when: "ansible_distribution_major_version <= '16'"

- name: Ensuring PHP72-FPM is Started (Ubuntu 14+)
  service:
    name={{ php72_fpm_service_name }}
    state=started
  when: "ansible_distribution_major_version >= '17'"

- name: Configuring RadiusDesk Cron Jobs (Ubuntu 14+)
  template:
    src="cron/cron.j2"
    dest="/etc/cron.d/rd"

- name: Disabling MySQL 5.7 Strict Mode (Ubuntu 16+)
  template:
    src="disable_strict_mode.cnf.j2"
    dest="/etc/mysql/conf.d/disable_strict_mode.cnf"
  when: "ansible_distribution_major_version >= '16'" 

- name: Ensuring MySQL is Started (Ubuntu 14+)
  service:
    name={{ mysql_service_name }}
    state=started

- name: Ensuring MySQL Root password has been set (Ubuntu 14+)
  stat:
    path={{ mysql_my_cnf }}
  register: mysql_conf

- name: Changing MySQL Root password (Ubuntu 14+)
  mysql_user:
    name=root
    host={{ item }}
    password={{ mysql_root_password }}
    state=present
  with_items: "{{ mysql_db_hosts }}"
  notify:
    - Restart MySQL
  when: mysql_conf.stat.exists == False

- name: Adding .my.cnf for MySQL root Password Idempotency (Ubuntu 14+)
  template:
    src="my.cnf.j2"
    dest={{ mysql_my_cnf }}
  when: mysql_conf.stat.exists == False

- name: Remove Anonymous MySQL Users (Ubuntu 14+)
  mysql_user:
    name=''
    host={{ item }}
    state=absent
    login_user=root
    login_password={{ mysql_root_password }}
  with_items: "{{ mysql_db_hosts }}"

- name: Creating RadiusDesk Database on AWS RDS (Ubuntu 14+)
  mysql_db:
    name={{ rd_db_name }}
    state=present
    login_user={{ aws_rds_user }}
    login_password={{ aws_rds_password }}
    login_host={{ aws_rds_host }}
    login_port={{ aws_rds_port }}
  when: enable_aws_rds_support

- name: Creating RadiusDesk Database (Ubuntu 14+)
  mysql_db:
    name={{ rd_db_name }}
    state=present
    login_user=root
    login_password={{ mysql_root_password }}

- name: Creating RadiusDesk Database User (Ubuntu 14+)
  mysql_user:
    "name={{ rd_db_user }}
    password={{ rd_db_password }}
    priv={{ rd_db_name }}.*:ALL
    state=present
    login_user=root
    login_password={{ mysql_root_password }}
    host={{ item }}"
  with_items: "{{ mysql_db_hosts }}"

- name: Creating RadiusDesk Database User on AWS RDS (Ubuntu 14+)
  mysql_user:
    "name={{ rd_db_user }}
    password={{ rd_db_password }}
    priv={{ rd_db_name }}.*:ALL
    state=present
    login_user={{ aws_rds_user }}
    login_password={{ aws_rds_password }}
    login_host={{ aws_rds_host }}
    login_port={{ aws_rds_port }}
    host={{ item }}"
  with_items: "{{ aws_rds_db_hosts }}"
  when: enable_aws_rds_support

- name: Copying RADIUSDesk Database SQL File for AWS RDS (Ubuntu 14+)
  shell: cp -a {{ nginx_webroot }}/cake3/rd_cake/setup/db/rd.sql {{ temp_src_dir | quote }}/rd_aws.sql
  when: enable_aws_rds_support

- name: Updating RADIUSDesk Database for AWS RDS (Ubuntu 14+)
  shell: sed -i.bk "s/DEFINER=\`root\`@\`localhost\`/DEFINER=CURRENT_USER /g" {{ temp_src_dir | quote }}/rd_aws.sql
  when: enable_aws_rds_support

- name: Importing RadiusDesk Database (Ubuntu 14+)
  mysql_db:
    state=import
    name={{ rd_db_name }}
    target={{ nginx_webroot }}/cake3/rd_cake/setup/db/rd.sql
    login_user=root
    login_password={{ mysql_root_password }}

- name: Importing RadiusDesk Database to AWS RDS (Ubuntu 14+)
  mysql_db:
    state=import
    name={{ rd_db_name }}
    target={{ temp_src_dir | quote }}/rd_aws.sql
    login_user={{ rd_db_user }}
    login_password={{ rd_db_password }}
    login_host={{ aws_rds_host }}
    login_port={{ aws_rds_port }}
  when: enable_aws_rds_support

- name: Updating RADIUSDesk Cake 2 Database Credentials (Ubuntu 14+)
  template:
    src="rd/c2/database.php.j2"
    dest="{{ nginx_webroot }}/cake2/rd_cake/Config/database.php"

- name: Updating RADIUSDesk Cake 3 Database Credentials (Ubuntu 14+)
  template:
    src="rd/c3/app.php.j2"
    dest="{{ nginx_webroot }}/cake3/rd_cake/config/app.php"
