#!/bin/bash

# Description: This project tries to simplify or ease the process of getting a working installation of RadiusDESK on a vanilla/minimal installation of RHEL/CentOS 6.X (32 bit/64 bit).
# Author: Mfawa Alfred Onen
# Link/URL: http://muffycompo.github.io/radiusdesk-installer
# Date: March 09, 2014
# Usage: ./rd_installer.sh
# Version: 1.0

# Ensure variables, functions and prompts exist
if [[ ! -e "includes/variables.sh" ]] || [[ ! -e "includes/functions.sh" ]] || [[ ! -e "includes/prompts.sh" ]]; then
	echo "We can not start the installer because some files are missing, try re-downloading the installer!"
	exit 1
else
	source includes/variables.sh
	source includes/functions.sh
	source includes/prompts.sh
fi

# Prompt for web server technology
ask_for_webserver

########## KICKSTART & PACKAGES ##############

# Check if user is Root
echo -n "Checking if you are root: "
check_root_privileges

# Check if SELinux is disabled
echo -n "Checking if SELinux is enabled: "
check_selinux_status

# Flush iptable rules -> TODO: Revert to a more secure system
#echo -n "Flushing default Iptable rules: "
reset_iptables_rules

# Install some packages from base repo
echo -e "Installing ${LIGHT_BLUE}${BOLD}pre-requisite packages${F_END}\n"
yum_install nano curl wget unzip
 
# Install EPEL/POPTOP repo
echo -e "Installing ${LIGHT_BLUE}${BOLD}EPEL Repository${F_END}\n"
install_epel_repo ${OS_VERSION} ${ARCH_TYPE}

# Install required packages
echo -e "Installing ${LIGHT_BLUE}${BOLD}required packages${F_END}\n"
yum_install ${webserver} php php-fpm php-pear php-gd php-common php-cli php-mysql php-xcache mysql-server mysql subversion git vixie-cron mailx python perl unixODBC postgresql krb5 openldap libtool-ltdl gcc-c++ gcc make pptpd

# Download & Install RHEL/CentOS 6 FreeRADIUS RPMs -> TODO: Compile RPMs for more OS_VERSIONS
install_mao_repo ${ARCH_TYPE}


########### RADIUSDESK REQUIREMENTS ###########

# Prepare Temp directory for downloaded files
mk_temp_dir

# Download CakePHP 2.2.9 -> TODO: Find a way to make this version agnostic
echo -e "Downloading ${LIGHT_BLUE}${BOLD}CakePHP 2.2.9${F_END}\n"
wget_download https://github.com/cakephp/cakephp/archive/2.2.9.zip ${TEMP_PATH}cakephp-2.2.9.zip

# Download Ext.Js 4.2.1
echo -e "Downloading ${LIGHT_BLUE}${BOLD}Ext.JS 4.2.1${F_END}\n"
wget_download http://sourceforge.net/p/radiusdesk/code/HEAD/tree/extjs/ext-4.2.1-gpl.zip?format=raw ${TEMP_PATH}ext-4.2.1-gpl.zip

# Download RADIUSdesk Source
echo -e "Downloading ${LIGHT_BLUE}${BOLD}RADIUSdesk SVN sources${F_END}\n"
svn --quiet checkout http://svn.code.sf.net/p/radiusdesk/code/trunk ${TEMP_PATH}source > /dev/null 2>&1

# Download NodeJS Source
echo -e "Downloading ${LIGHT_BLUE}${BOLD}NodeJS 0.10.26 source${F_END}\n"
wget_download http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz ${TEMP_PATH}node-v0.10.26.tar.gz

########### RADIUSDESK COMPONENT INSTALLATION ###########

# Use web server to install to default location -> TODO: Might be useful to allow user input
if [[ "${webserver}" = "nginx" ]]; then
	
	# Document Root
	HTTP_DOCUMENT_ROOT='/usr/share/nginx/html/'
	
	# Copy nginx configuration files
	copy_nginx_configs ${CONF_DIR}
	
	# Start services needed by RADIUSdesk
	echo -e "Starting ${LIGHT_BLUE}${BOLD}services${F_END} needed by RADIUSdesk\n"
	start_service_on_boot php-fpm
	start_service php-fpm
	start_service ${webserver}
	
elif [[ "${webserver}" = "httpd" ]]; then
	HTTP_DOCUMENT_ROOT='/var/www/html/'
	
	# Copy apache configuration files
	copy_apache_configs ${CONF_DIR}
	
	# Start services needed by RADIUSdesk
	echo -e "Starting ${LIGHT_BLUE}${BOLD}services${F_END} needed by RADIUSdesk\n"
	start_service ${webserver}
else
	echo -e "${LIGHT_RED}${BOLD}Something happened and we can not configure your system${F_END}\n"
	exit 1
fi

# Start services needed by RADIUSdesk contd.
start_service mysqld

# Get to tmp directory where the action begins
get_to ${TEMP_PATH}

# Install CakePHP
echo -e "Installing ${LIGHT_BLUE}${BOLD}CakePHP${F_END}\n"
install_cakephp ${TEMP_PATH} ${HTTP_DOCUMENT_ROOT}

# Install rd_cake, rd2, meshdesk, rd_clients, rd_login_pages
echo -e "Installing ${LIGHT_BLUE}${BOLD}RADIUSdesk${F_END}\n"
install_radiusdesk ${TEMP_PATH} ${SOURCE_DIR} ${HTTP_DOCUMENT_ROOT}

echo -e "Installing ${LIGHT_BLUE}${BOLD}Ext.JS${F_END}\n"
install_extjs ${TEMP_PATH} ${HTTP_DOCUMENT_ROOT}

# RADIUSdesk cron script
echo -e "Installing ${LIGHT_BLUE}${BOLD}Cron Script${F_END} for RADIUSdesk\n"
install_radiusdesk_cron ${HTTP_DOCUMENT_ROOT} ${webserver}

echo -e "Updating ${LIGHT_BLUE}${BOLD}RADIUSdesk Paths${F_END} for RHEL/CentOS compatibility\n"
update_radiusdesk_paths ${HTTP_DOCUMENT_ROOT}

# Import sql file to database
echo -e "Installing ${LIGHT_BLUE}${BOLD}Database Schema${F_END} for RADIUSdesk\n"
install_radiusdesk_schema ${HTTP_DOCUMENT_ROOT}

# FreeRADIUS configuration
configure_radiusdesk_freeradius ${HTTP_DOCUMENT_ROOT} ${RADIUS_DIR}

# Disabled TTY Requirements for Sudoers
fix_radiusdesk_sudoers ${SUDOERS_FILE} ${HTTP_DOCUMENT_ROOT}

########### RADIUSDESK OWNERSHIP AND PERMISSIONS ###########
# Update Ownership and Permissions
fix_radiusdesk_permissions_ownership ${HTTP_DOCUMENT_ROOT}

# NodeJS Installation
echo -e "Installing ${LIGHT_BLUE}${BOLD}NodeJS${F_END}\n"
install_nodejs ${TEMP_PATH} ${HTTP_DOCUMENT_ROOT} /etc/init.d/

# Make things start on boot
start_service_on_boot nodejs-socket-io
start_service_on_boot ${webserver}
start_service_on_boot radiusd
start_service_on_boot pptpd
start_service_on_boot mysqld

# Start/Restart services
echo -e "Checking if services are ${LIGHT_BLUE}${BOLD}fully Operational${F_END}\n"
start_service nodejs-socket-io
restart_service ${webserver}
start_service radiusd
start_service pptpd

# Clear temporary directory
clear_dir ${TEMP_PATH}

# RADIUSdesk Installation complete
echo -e "\n"
echo -e "${LIGHT_GREEN}${BOLD}INSTALLATION COMPLETED SUCCESSFULLY!!!${F_END}\n"
echo -e "To access your RADIUSdesk server, visit ${LIGHT_GREEN}${BOLD}http://${IP_ADDRESS}/rd${F_END} on your browser\n"
echo -e "USERNAME: ${LIGHT_BLUE}${BOLD}root${F_END}  PASSWORD: ${LIGHT_BLUE}${BOLD}admin${F_END}\n\n"
echo -e "We recommend ${LIGHT_RED}${BOLD}rebooting${F_END} your computer to ensure everything went as planned :)\n"

# Prompt User to reboot
ask_for_reboot

# END