#!/bin/bash

# Description: This project tries to simplify or ease the process of getting a working installation of RadiusDESK on a vanilla/minimal installation of RHEL/CentOS 6.X (32 bit/64 bit).
# Author: Mfawa Alfred Onen
# Link/URL: http://muffycompo.github.io/radiusdesk-installer
# Date: March 14, 2014
# Usage: ./rd-installer or ./rd-installer -v|--version

# Include Menu
source includes/menu.sh

# Show RADIUSdesk Installer Version when -v is passed to Installer
show_version ${1}

installer_menu

# END